#!/bin/bash
MONITORDIR="/afs/math.uni-hamburg.de/users/stud/baw9537/simulation/2023 11 24/hdiv/output/data/"
TARGETDIR="$(pwd)/data/"  # "$(pwd)" is working direcotry
CHECKSECS=1
DELAYSECS=20
oldFiles="old"
extensions=( ".vtu" ".pvtu" )

MONITORDIRORG=$MONITORDIR
#MONITORDIR=${MONITORDIR// /"\ "}
#TARGETDIR=${TARGETDIR// /"\ "}


moveDelayed () {
	/bin/sleep ${DELAYSECS}
	FILEPATH="${MONITORDIR}/$1"
	echo "moving ${FILEPATH} to ${TARGETDIR}"
	/bin/mv "${FILEPATH}" "${TARGETDIR}"
}

#inotifywait -m -r -e create "${MONITORDIR}" | while read PATH ACTION FILE

while :
do
 	allFilesNow=$(ls "$MONITORDIR")
 	if [ "$allFilesNow" != "$allFilesPrev" ]
	then
#		echo $allFilesNow
		#echo $allFilesPrev
#		diff  <(echo "$allFilesPrev" ) <(echo "$allFilesNow")
		newFiles=$(comm -23 <(echo "$allFilesNow" | sort) <(echo "$allFilesPrev" | sort))
		files=( $newFiles )
		for file in "${files[@]}"; do
			extensionCorrect="false"
			for extension in "${extensions[@]}"; do
				if [[ $file == *"$extension" ]]
				then
					extensionCorrect="true"
				fi
			done
#			echo "$file"
#			echo "$extensionCorrect"
			if [[ $extensionCorrect == *"true" ]]
			then			
				echo -n "$file "
				moveDelayed "$file" &
			fi
		done 
	else
		echo -n "."
	fi
	allFilesPrev="$allFilesNow"
#	FILEPATH="${PATH}${FILE}"
	/bin/sleep ${CHECKSECS}
done
