#!/bin/bash
MONITORDIR="/afs/math.uni-hamburg.de/users/stud/baw9537/simulation/2023 11 24/hdiv/output/data/"
TARGETDIR="$(pwd)/data/"  # "$(pwd)" is working direcotry
CHECKSECS=1
DELAYSECS=20
oldFiles="old"
moveExtensions=( ".vtu" ".pvtu" )
copyExtensions=( ".pvd" )



moveDelayed () {
	/bin/sleep ${DELAYSECS}
	FILEPATH="${MONITORDIR}/$1"
	echo "moving ${FILEPATH} to ${TARGETDIR}"
	/bin/mv "${FILEPATH}" "${TARGETDIR}"
}


copyFile () {
	FILEPATH="${MONITORDIR}/$1"
	echo "copying ${FILEPATH} to ${TARGETDIR}"
	/bin/cp "${FILEPATH}" "${TARGETDIR}"
}

#inotifywait -m -r -e create "${MONITORDIR}" | while read PATH ACTION FILE

while :
do
 	allFilesNow=$(ls "$MONITORDIR")
 	if [ "$allFilesNow" != "$allFilesPrev" ]
	then
		newFiles=$(comm -23 <(echo "$allFilesNow" | sort) <(echo "$allFilesPrev" | sort))
		files=( $newFiles )
		
		### files to move
		for file in "${files[@]}"; do
			extensionCorrect="false"
			for extension in "${moveExtensions[@]}"; do
				if [[ $file == *"$extension" ]]
				then
					extensionCorrect="true"
				fi
			done
			if [[ $extensionCorrect == "true" ]]
			then			
				echo -n "$file "
				moveDelayed "$file" &
			fi
			
		done
		
		
		### files to copy
		allFiles=( $allFilesNow )
		for file in "${allFiles[@]}"; do
			extensionCorrect="false"
			for extension in "${copyExtensions[@]}"; do
				if [[ $file == *"$extension" ]]
				then
					extensionCorrect="true"
				fi
			done
			if [[ $extensionCorrect == "true" ]]
			then			
				#echo -n "$file "
				copyFile "$file" &
			fi
		done
		
	else
		echo -n "."
	fi
	allFilesPrev="$allFilesNow"
	/bin/sleep ${CHECKSECS}
done
